# Generated by Django 5.2.7 on 2025-10-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='certification_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='certification_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='certification_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
